---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.9.4"
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.31.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint

  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.8
    hooks:
      - id: ripsecrets
        args:
          - "--additional-pattern=[A-z0-9/+]{86}=="
