---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.6"
    hooks:
      - id: ruff
      - id: ruff-format
      - id: ruff-format

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.27.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "3.1.15"
    hooks:
      - id: checkov
