trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  serviceConnection: "example-federated-sc"

jobs:
  - job: deployInfrastructure
    displayName: "Deploy the infrastructure"
    steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: "1.9.1"

      - task: TerraformTaskV4@4
        displayName: "Initialize Terraform"
        inputs:
          provider: "azurerm"
          command: "init"
          workingDirectory: "$(System.DefaultWorkingDirectory)/ops"
          backendServiceArm: $(serviceConnection)
          backendAzureRmResourceGroupName: "deploy-rg"
          backendAzureRmStorageAccountName: "generaltfstatesta"
          backendAzureRmContainerName: "tf-state"
          backendAzureRmKey: "terraform.tfstate"

      - task: TerraformTaskV4@4
        name: terraformPlan
        displayName: Create Terraform Plan
        inputs:
          provider: "azurerm"
          command: "plan"
          commandOptions: "-out main.tfplan"
          environmentServiceNameAzureRM: $(serviceConnection)
          workingDirectory: "$(System.DefaultWorkingDirectory)/ops"
