trigger: none

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: azureFunctionProgrammingModel
    displayName: "Azure Function Programming Model"
    type: string
    values:
      - v1
      - v2

variables:
  serviceConnection: "example-federated-sc"

  ${{ if eq(parameters.azureFunctionProgrammingModel, 'v1') }}:
    functionAppName: "af-v1-dev9d"
    functionAppPath: "v1"

  ${{ if eq(parameters.azureFunctionProgrammingModel, 'v2') }}:
    functionAppName: "af-dev9d"
    functionAppPath: "v2"

jobs:
  - job: deployAF
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"
          addToPath: true
          architecture: "x64"
        displayName: "Use Python 3.12"

      - task: AzureCLI@2
        displayName: Add agent ip to key vault firewall
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            agentIP=$(curl -s https://checkip.amazonaws.com)
            az keyvault network-rule add --name "af-kv-dev9d" --ip-address "$agentIP" --only-show-errors

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: "$(serviceConnection)"
          KeyVaultName: "af-kv-dev9d"
          SecretsFilter: "*"
          RunAsPreJob: false

      - bash: |
          python -m pip install --upgrade pip && \
          python -m pip install poetry~="1.8" poetry-plugin-export
        displayName: "Install poetry"

      - bash: |
          python -m poetry export -f requirements.txt --without-hashes > requirements.txt
        displayName: "Export dependencies"

      - bash: |
          python -m pip install -t "$(functionAppPath)/.python_packages/lib/site-packages" \
          -r requirements.txt
        displayName: "Install dependencies"

      - task: ArchiveFiles@2
        displayName: "Archive files"
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)/$(functionAppPath)"
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/build$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/build$(Build.BuildId).zip"
          artifactName: "drop"

      - task: AzureFunctionApp@2
        inputs:
          azureSubscription: "$(serviceConnection)"
          appType: "functionAppLinux"
          appName: $(functionAppName)
          package: "$(Pipeline.Workspace)/**/build$(Build.BuildId).zip"
          appSettings: >
            -STA_CONN_STRING $(STA-CONN-STRING)
            -AZ_STA_NAME $(AZ-STA-NAME)
            -AZ_STA_KEY $(AZ-STA-KEY)
            -STA_MI_CONN__blobServiceUri $(STA-BLOB-URI)
            -STA_MI_CONN__queueServiceUri $(STA-QUEUE-URI)

      - task: AzureCLI@2
        displayName: Remove Agent IP From Key Vault
        condition: always()
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            agentIP=$(curl -s https://checkip.amazonaws.com)
            az keyvault network-rule remove --name "af-kv-dev9d" --ip-address "$agentIP" --only-show-errors
