trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  serviceConnection: "example-federated-sc"

jobs:
  - job: deployInfrastructure
    displayName: "Deploy the infrastructure"
    steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: "0.14.8"

      - task: TerraformTaskV1@0
        inputs:
          provider: "azurerm"
          command: "init"
          workingDirectory: "$(System.DefaultWorkingDirectory)/ops/stack"
          environmentServiceNameAzureRM: "<Your ARM service connection>"

      - task: TerraformTaskV1@0
        inputs:
          provider: "azurerm"
          command: "plan"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
          environmentServiceNameAzureRM: "<Your ARM service connection>"

      - task: TerraformTaskV1@0
        inputs:
          provider: "azurerm"
          command: "apply"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
          environmentServiceNameAzureRM: "<Your ARM service connection>"
          commandOptions: "-auto-approve"
