trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  serviceConnection: "example-federated-sc"

jobs:
  - job: deployInfrastructure
    displayName: "Deploy the infrastructure"
    steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: "1.9.1"

      - task: TerraformTaskV3@3
        displayName: "Initialize Terraform"
        inputs:
          provider: "azurerm"
          command: "init"
          workingDirectory: "$(System.DefaultWorkingDirectory)/ops"
          environmentServiceNameAzureRM: $(serviceConnection)
          backendAzureRmResourceGroupName:

      - task: TerraformTaskV3@3
        displayName: "Plan"
        inputs:
          provider: "azurerm"
          command: "plan"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
          environmentServiceNameAzureRM: $(serviceConnection)

      - task: TerraformTaskV3@3
        displayName: "Apply"
        inputs:
          provider: "azurerm"
          command: "apply"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
          environmentServiceNameAzureRM: $(serviceConnection)
          commandOptions: "-auto-approve"
